/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HonorsRouteImport } from './routes/honors'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StagesIndexRouteImport } from './routes/stages.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as AdmissionsIndexRouteImport } from './routes/admissions.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as StagesMiddleRouteImport } from './routes/stages.middle'
import { Route as StagesHighRouteImport } from './routes/stages.high'
import { Route as StagesElementaryRouteImport } from './routes/stages.elementary'
import { Route as NewsUpdatesRouteImport } from './routes/news.updates'
import { Route as NewsCalendarRouteImport } from './routes/news.calendar'
import { Route as AdmissionsTuitionRouteImport } from './routes/admissions.tuition'
import { Route as AboutPrincipalRouteImport } from './routes/about.principal'
import { Route as AboutMissionRouteImport } from './routes/about.mission'
import { Route as AboutLeadershipRouteImport } from './routes/about.leadership'

const HonorsRoute = HonorsRouteImport.update({
  id: '/honors',
  path: '/honors',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesIndexRoute = StagesIndexRouteImport.update({
  id: '/stages/',
  path: '/stages/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsIndexRoute = AdmissionsIndexRouteImport.update({
  id: '/admissions/',
  path: '/admissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesMiddleRoute = StagesMiddleRouteImport.update({
  id: '/stages/middle',
  path: '/stages/middle',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesHighRoute = StagesHighRouteImport.update({
  id: '/stages/high',
  path: '/stages/high',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesElementaryRoute = StagesElementaryRouteImport.update({
  id: '/stages/elementary',
  path: '/stages/elementary',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsUpdatesRoute = NewsUpdatesRouteImport.update({
  id: '/news/updates',
  path: '/news/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsCalendarRoute = NewsCalendarRouteImport.update({
  id: '/news/calendar',
  path: '/news/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsTuitionRoute = AdmissionsTuitionRouteImport.update({
  id: '/admissions/tuition',
  path: '/admissions/tuition',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPrincipalRoute = AboutPrincipalRouteImport.update({
  id: '/about/principal',
  path: '/about/principal',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMissionRoute = AboutMissionRouteImport.update({
  id: '/about/mission',
  path: '/about/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutLeadershipRoute = AboutLeadershipRouteImport.update({
  id: '/about/leadership',
  path: '/about/leadership',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/honors': typeof HonorsRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/principal': typeof AboutPrincipalRoute
  '/admissions/tuition': typeof AdmissionsTuitionRoute
  '/news/calendar': typeof NewsCalendarRoute
  '/news/updates': typeof NewsUpdatesRoute
  '/stages/elementary': typeof StagesElementaryRoute
  '/stages/high': typeof StagesHighRoute
  '/stages/middle': typeof StagesMiddleRoute
  '/about/': typeof AboutIndexRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/stages/': typeof StagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/honors': typeof HonorsRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/principal': typeof AboutPrincipalRoute
  '/admissions/tuition': typeof AdmissionsTuitionRoute
  '/news/calendar': typeof NewsCalendarRoute
  '/news/updates': typeof NewsUpdatesRoute
  '/stages/elementary': typeof StagesElementaryRoute
  '/stages/high': typeof StagesHighRoute
  '/stages/middle': typeof StagesMiddleRoute
  '/about': typeof AboutIndexRoute
  '/admissions': typeof AdmissionsIndexRoute
  '/news': typeof NewsIndexRoute
  '/stages': typeof StagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/honors': typeof HonorsRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/mission': typeof AboutMissionRoute
  '/about/principal': typeof AboutPrincipalRoute
  '/admissions/tuition': typeof AdmissionsTuitionRoute
  '/news/calendar': typeof NewsCalendarRoute
  '/news/updates': typeof NewsUpdatesRoute
  '/stages/elementary': typeof StagesElementaryRoute
  '/stages/high': typeof StagesHighRoute
  '/stages/middle': typeof StagesMiddleRoute
  '/about/': typeof AboutIndexRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/stages/': typeof StagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/honors'
    | '/about/leadership'
    | '/about/mission'
    | '/about/principal'
    | '/admissions/tuition'
    | '/news/calendar'
    | '/news/updates'
    | '/stages/elementary'
    | '/stages/high'
    | '/stages/middle'
    | '/about/'
    | '/admissions/'
    | '/news/'
    | '/stages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/honors'
    | '/about/leadership'
    | '/about/mission'
    | '/about/principal'
    | '/admissions/tuition'
    | '/news/calendar'
    | '/news/updates'
    | '/stages/elementary'
    | '/stages/high'
    | '/stages/middle'
    | '/about'
    | '/admissions'
    | '/news'
    | '/stages'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/honors'
    | '/about/leadership'
    | '/about/mission'
    | '/about/principal'
    | '/admissions/tuition'
    | '/news/calendar'
    | '/news/updates'
    | '/stages/elementary'
    | '/stages/high'
    | '/stages/middle'
    | '/about/'
    | '/admissions/'
    | '/news/'
    | '/stages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  HonorsRoute: typeof HonorsRoute
  AboutLeadershipRoute: typeof AboutLeadershipRoute
  AboutMissionRoute: typeof AboutMissionRoute
  AboutPrincipalRoute: typeof AboutPrincipalRoute
  AdmissionsTuitionRoute: typeof AdmissionsTuitionRoute
  NewsCalendarRoute: typeof NewsCalendarRoute
  NewsUpdatesRoute: typeof NewsUpdatesRoute
  StagesElementaryRoute: typeof StagesElementaryRoute
  StagesHighRoute: typeof StagesHighRoute
  StagesMiddleRoute: typeof StagesMiddleRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AdmissionsIndexRoute: typeof AdmissionsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  StagesIndexRoute: typeof StagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/honors': {
      id: '/honors'
      path: '/honors'
      fullPath: '/honors'
      preLoaderRoute: typeof HonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages/': {
      id: '/stages/'
      path: '/stages'
      fullPath: '/stages/'
      preLoaderRoute: typeof StagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/': {
      id: '/admissions/'
      path: '/admissions'
      fullPath: '/admissions/'
      preLoaderRoute: typeof AdmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages/middle': {
      id: '/stages/middle'
      path: '/stages/middle'
      fullPath: '/stages/middle'
      preLoaderRoute: typeof StagesMiddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages/high': {
      id: '/stages/high'
      path: '/stages/high'
      fullPath: '/stages/high'
      preLoaderRoute: typeof StagesHighRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages/elementary': {
      id: '/stages/elementary'
      path: '/stages/elementary'
      fullPath: '/stages/elementary'
      preLoaderRoute: typeof StagesElementaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/updates': {
      id: '/news/updates'
      path: '/news/updates'
      fullPath: '/news/updates'
      preLoaderRoute: typeof NewsUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/calendar': {
      id: '/news/calendar'
      path: '/news/calendar'
      fullPath: '/news/calendar'
      preLoaderRoute: typeof NewsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/tuition': {
      id: '/admissions/tuition'
      path: '/admissions/tuition'
      fullPath: '/admissions/tuition'
      preLoaderRoute: typeof AdmissionsTuitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/principal': {
      id: '/about/principal'
      path: '/about/principal'
      fullPath: '/about/principal'
      preLoaderRoute: typeof AboutPrincipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/mission': {
      id: '/about/mission'
      path: '/about/mission'
      fullPath: '/about/mission'
      preLoaderRoute: typeof AboutMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/leadership': {
      id: '/about/leadership'
      path: '/about/leadership'
      fullPath: '/about/leadership'
      preLoaderRoute: typeof AboutLeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  HonorsRoute: HonorsRoute,
  AboutLeadershipRoute: AboutLeadershipRoute,
  AboutMissionRoute: AboutMissionRoute,
  AboutPrincipalRoute: AboutPrincipalRoute,
  AdmissionsTuitionRoute: AdmissionsTuitionRoute,
  NewsCalendarRoute: NewsCalendarRoute,
  NewsUpdatesRoute: NewsUpdatesRoute,
  StagesElementaryRoute: StagesElementaryRoute,
  StagesHighRoute: StagesHighRoute,
  StagesMiddleRoute: StagesMiddleRoute,
  AboutIndexRoute: AboutIndexRoute,
  AdmissionsIndexRoute: AdmissionsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  StagesIndexRoute: StagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
